### ISSUE TITLE
Clicking the mouse scroll wheel doesn't move the canvas around anymore

### ISSUE THREAD

**Issue by mpmo10** [zero01101/openOutpaint#102]
I used to be able to move the canvas around by clicking and holding the mouse scroll wheel and then moving my mouse up, down, left, right. But now I can't. I'm on the latest version (git pull)

**Comment by zero01101** [comment]
lol, yep, if you're on testing then you're probably one of the folks i was talking about in [this thread](https://github.com/zero01101/openOutpaint/pull/100#issuecomment-1353259027) - essentially, the pan and zoom controls are going to live underneath the [`CTRL`] button as basically a "camera control" modifier because of how the mouse inputs are handled for interacting with the images themselves (middle-click being the shockingly useful shortcut to "make more", scrolling through the batches, approve/reject by click)

**Comment by mpmo10** [comment]
Ohh ok thanks for letting me know, will close this issue then
