### ISSUE TITLE
[Bug]: Outputs very pixelated / low bitrate looking when img2img is used on sketch

### ISSUE THREAD

**Issue by artreloaded** [zero01101/openOutpaint#189]
### What happened?

I thought about using openOutpaint as a sketch editor to first paint a white surface and then paint a crude hammer on it (pictures below). I then intended to use img2img on it to get an object that can be cut out later, but the outputs are very pixelated. "Affect mask" was turned off. Inpainting model selected. Denoise was too high (didnt hold the form) but lower denoise didnt change the pixelated appearance.

![Annotation 2023-01-29 060139](https://user-images.githubusercontent.com/123234324/215306068-c7c7c7ba-2681-49ed-94fe-ae3eb19be6a7.png)
![Annotation 2023-01-29 060200](https://user-images.githubusercontent.com/123234324/215306072-12a68d56-3b8d-4d31-aa16-49f2028db8c1.png)

I also noticed that if I use txt2img on an empty surface with prompt+neg. prompt the results are... really strange, like this:

![Annotation 2023-01-29 060629](https://user-images.githubusercontent.com/123234324/215306153-7cd6a43a-3a08-40b4-9db8-7fc29f01e852.png)

Its as if openOutpaint has problems processing against the empty background, even if it is painted over

### Steps to reproduce the problem

Its in the description

### What should have happened?

usual renders

### Commit where the problem happens

newest

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

None that would be relevant. Also tried running in private window which didnt change it

### AUTOMATIC1111 webUI Commandline Arguments

--xformers --api

**Comment by zero01101** [comment]
i kind of suspect this might be related to the model you're using as that's definitely a supported use case

![image](https://user-images.githubusercontent.com/1649724/215306492-8ef02abb-62a3-4b9d-b295-50ec488a5fd7.png)
![image](https://user-images.githubusercontent.com/1649724/215306505-cb0ac338-0bf9-46d1-b231-1ae132cb4ae5.png)
![image](https://user-images.githubusercontent.com/1649724/215306511-d5271e97-8335-4f75-a5f5-ad416a9a9983.png)
![image](https://user-images.githubusercontent.com/1649724/215306544-dc93bcbe-b1c8-41f7-b3db-19ca109bd270.png)
![image](https://user-images.githubusercontent.com/1649724/215306553-f7eed38a-98c7-4c54-a06a-213f2cc82e8f.png)

>I also noticed that if I use txt2img on an empty surface with prompt+neg. prompt the results are... really strange, like this:

txt2img meaning the dream tool? 

openOutpaint's default parameters definitely use both positive and negative prompts and both work as expected; this "test image" of mine has proven to be a very reliable test of determinism

![image](https://user-images.githubusercontent.com/1649724/215306703-546be939-63ba-4fad-bf09-046246c5627f.png)

your image _really_ feels like your issue is going to be the model you're using or possibly you've got resolution and reticle size set... really mismatched?  

do you get those results using [runwayML 1.5](https://huggingface.co/stabilityai/stable-diffusion-2-inpainting/tree/main) or [stabilityAI 2.0](https://huggingface.co/stabilityai/stable-diffusion-2-inpainting/tree/main) inpainting models using 512x512 matched resolution/reticle?

**Comment by zero01101** [comment]
oh! regarding the txt2img issues, you don't possibly have [hrfix enabled with a high scale factor](https://github.com/zero01101/openOutpaint/wiki/Manual#gear), do you?

**Comment by artreloaded** [comment]
Hm, no I dont have it on 4. And the SD model is the usual 1.5 inpainting model, I dont know where I got it from, but I also included the VAE. It gives me very good results but only when I import something and then start to outpaint the borders. If I start empty its problematic

Im going to test it with another browser or re-download the model with the VAE.

**Comment by artreloaded** [comment]
Yea I found the error. I unchecked apply txt2img Hrfix and it works now. I was under the impression that txt2img hrfix is disabled by default if I only use 512x512. That explains everything!
