### ISSUE TITLE
[Feature Request]: Multiple network support

### ISSUE THREAD

**Issue by unai-ndz** [zero01101/openOutpaint#215]
### Is your feature request related to a problem? Please describe.

Afaik right now you can only use extra networks like loras by enabling one at a time in the SD webui settings.

### Describe the solution you'd like

I would like for openOutpaint to support serveral networks, either by itself or making use of another extension.

### Proposed workflow

Looks like the prompt syntax <lora_name:weight> is already supported but it only activates the one in SD settings. The UI for this extension is already a bit crowded so leaving loras to be activated using the prompt looks reasonable.

### Describe alternatives you've considered

Making use of the activated loras in the txt2img or img2img tab, we avoid crowding the UI but changing tab is needed.

### Additional context

In case this gets added this extension[extension](https://github.com/kohya-ss/sd-webui-additional-networks) seems a good candidate for both supporting as the network enabler in another tab or for seen how it enables multiple networks.

PD: Do loras even work properly with inpainting models? I seem to get worse results than with txt2img but I'm not sure if it is that, only using one lora or just the nature of inpainting

**Comment by zero01101** [comment]
so as you mentioned, prompt-addition syntax is pretty much the only current support - there's an API endpoint for listing hypernetworks (which _don't_ seem to have any affect on inpainting models), as well as textual inversions, but seemingly no endpoint for LoRAs? 

openOutpaint's strictly vanilla JS/HTML, no python here; the [webUI extension](https://github.com/zero01101/openOutpaint-webUI-extension) uses a minimal amount for the (required) webUI tab, (useless) API hook, and (useful) `send to openOutpaint` buttons but otherwise is still just the same JS/HTML app so there's probably a rather slim chance of much more python being incorporated anywhere... but basically, once there's an API endpoint to list LoRAs along with hypernets and embeddings, it'll be a lot more consistent and reasonable to consider implementing them as a UI option :)

all that being said, quick tests show LoRAs (randomly selected from civitAI) definitely work on inpainting models (runwayML SD1.5 tested) in both openOutpaint as well as webUI directly and can be stacked using prompt syntax:

![image](https://user-images.githubusercontent.com/1649724/227391773-badebd1a-dd36-465f-b275-31ec9bcb7058.png)
![image](https://user-images.githubusercontent.com/1649724/227391878-43cb2d76-53c5-4df8-8fe3-cd285d4a3fe6.png)
![image](https://user-images.githubusercontent.com/1649724/227392057-7b8c4b8c-46c1-4ced-88fc-c560613a671a.png)
![image](https://user-images.githubusercontent.com/1649724/227392077-7bad2b8b-1072-4600-8902-fec217a2d0ed.png)
![image](https://user-images.githubusercontent.com/1649724/227392492-43fec4fe-0ea9-41a0-95f4-6bf9c2070b8e.png)
![image](https://user-images.githubusercontent.com/1649724/227392508-87127804-1dcb-4253-b4d3-fe4d34ce6c0c.png)
![image](https://user-images.githubusercontent.com/1649724/227392606-8ee10353-5515-4144-8043-bbfa280d7ed9.png)
![image](https://user-images.githubusercontent.com/1649724/227392904-5ff5a38e-5d55-438d-b2c9-30ae6a01f980.png)

**Comment by unai-ndz** [comment]
Thanks a lot. I had the syntax slightly wrong so they were not activating properly with just the prompt.
As you said maybe we can revisit this later when the webui has an api for it, hopefully in the correct repo for the extension this time.
