### ISSUE TITLE
[Bug]: can't paste the image above 4300px.

### ISSUE THREAD

**Issue by dendenis82** [zero01101/openOutpaint#231]
### What happened?

I can paste(ctrl+V) 4000x4000px but can`t paste 4300x4300px via "Select Image (S)".
Tried both Chrome and Edge.

### Steps to reproduce the problem

1. Go to image editor of your choice
2. Copy to buffer image bigger than 4000x4000px
3. Go to openOutpaint
4. Press "Select Image (S)"
5. Hover cursor over checker area and press Ctrl+V

### What should have happened?

I`ve expected large image to be imported over buffer, since Canvas Size Settings have no limits above 4300x4300px dimensions.  
![image](https://user-images.githubusercontent.com/21170174/236667010-4f6f1fbd-9278-4e26-a020-60e50a496030.png)

### Commit where the problem happens

5e84d6d5 (Mon Apr 10 23:01:41 2023)	

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Browser Extensions/Addons

uBlockOrigin
DarkReader
Authentificator
Chrome remote desktop

### AUTOMATIC1111 webUI Commandline Arguments

 --api --xformers 

### Additional information

ryzen 5600G, gtx 1060, 64ram,
If the problem due to some buffer restrictions, please, let us know.
I still able to import huge image via Image Stamp(U)-->Upload Image, but not so handy when it's need to be edited many times.

**Comment by zero01101** [comment]
terribly sorry for the extended delay; this project isn't abandoned but i've had to step away from it due to Reasons for a while, and i admit additional responses may (aka will probably) be delayed but hopefully not nearly as long

shockingly, i cannot confirm this and was really expecting to :| generated a 4400x4400 image and copied the contents, then pasted it and it... worked 

apologetically, i don't even know what kind of questions to ask to even begin on troubleshooting this one lol

![image](https://github.com/zero01101/openOutpaint/assets/1649724/ff49cff6-2109-4e30-813d-3b98c9ce15f6)

![image](https://github.com/zero01101/openOutpaint/assets/1649724/5d029b65-f8d6-42ec-9ac5-4edd7d9f806e)

![image](https://github.com/zero01101/openOutpaint/assets/1649724/e0bf8309-f1f8-4640-bd32-59c80bfed0f2)

**Comment by zero01101** [comment]
closing as stale
