### ISSUE TITLE
[Feature Request]: Completion of Generate More should switch to the new image.

### ISSUE THREAD

**Issue by vbmark** [zero01101/openOutpaint#242]
### Is your feature request related to a problem? Please describe.

When clicking the plus sign to Generate More, it is difficult to tell if the new image is complete.  Then, you must manually click the Next Image button (>) to see it.

### Describe the solution you'd like

When the generation of the new image is complete, the application should automatically switch to the new image.

### Proposed workflow

1. Use the Dream selector to select the range.
2. Press +
3. See new, completed image automatically with no further user input.

### Describe alternatives you've considered

Could not think of any alternative solutions or features.

### Additional context

Thank you.

**Comment by zero01101** [comment]
hey, sorry for the delay; i swear i tried implementing this and it didn't work as expected for some reason and i haven't had a chance to look at it since - just wanted you to know i haven't abandoned your feature request because yeah, that makes sense - likely as an option to keep compatibility with the current way it operates

**Comment by vbmark** [comment]
I appreciate the attempt.  Maybe one day it'll just come to you.  Thanks!

**Comment by zero01101** [comment]
yeah i was being an idiot like always apparently lol; updated in https://github.com/zero01101/openOutpaint/commit/674bdbe11b710668e29a8c776d900de243427afc - there's a checkbox in the config/options to enable it
