### ISSUE TITLE
What happens if you change the prompt after a Dream has been created and you press the + button?

### ISSUE THREAD

**Issue by rollzwiththepollz** [zero01101/openOutpaint#252]
### What happened?

1. Create Dream
2. Don't select Y or N
3. Change prompts
4. Press +

Does the new Dream created take the new prompt into account? Or do I have to press N and create a new Dream for the new prompt to take affect?

### Steps to reproduce the problem

1. Create Dream
2. Don't select Y or N
3. Change prompts
4. Press +

Does the new Dream created take the new prompt into account? Or do I have to press N and create a new Dream for the new prompt to take affect?

### What should have happened?

See above

### Commit where the problem happens

bf21c19

### What platforms do you use to access openOutpaint?

MacOS

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

None

### AUTOMATIC1111 webUI Commandline Arguments

See above

**Comment by zero01101** [comment]
well huh; i don't so much think it's a bug in that it's always been kind of a "more, please" button and i suppose i assumed "more, please" implied "more of the same thing, please", but i can absolutely see the value in tweaking the prompt... added in https://github.com/zero01101/openOutpaint/commit/674bdbe11b710668e29a8c776d900de243427afc, check the config window to enable the option since it's kind of a "breaking" change to existing functionality

**Comment by Kadah** [comment]
I wouldn't mind a new button that's "gen more with current prompt" or such.
