### ISSUE TITLE
checkerboard background origin Y-coord affected by devtools during page render (bleeding edge branch)

### ISSUE THREAD

**Issue by zero01101** [zero01101/openOutpaint#61]
- expected behavior: checkerboard background is static

- observed behavior: checkerboard background pans south if the page is rendered/refreshed with devtools open

![checkerboard](https://user-images.githubusercontent.com/1649724/204683652-ad6155b4-6926-42b2-8db4-aedb43a28ebb.gif)

**Comment by seijihariki** [comment]
This seems to be just the viewport keeping its center when resizing... I am uncertain if there is much we could do about this, unless we move the viewport manually when resizing.

Seeing the greenish background is expected behavior, as one can manually drag the viewport to there:

https://user-images.githubusercontent.com/7552751/204685596-39a354fd-0fda-4cb8-8f43-a3679f12ea1a.mp4

In this video, the pink point is the viewport center (also kind of the anchor point). What seems to be happening on devtools close, is that the viewport expanded, and the center was kept in-place. Not sure what we can do, as any solution I can think of worsens the problem if the viewport were to be extended to the other side. (ex. fix for expanding to the bottom would worsen the problems for expanding from the top).

**Comment by seijihariki** [comment]
Maybe we can, on resize, force the viewport back to fully inside the canvas. When the zoom is far enough to cover a full side of the canvas, we might as well center the viewport.

**Comment by zero01101** [comment]
honestly, i wonder if it's even a problem at all; like you said, the delightfully windows-98-colored background is expected to be seen on a pan, and yeah, it makes perfect sense that a viewport center is vertically higher on page render with the devtools open so this probably doesn't even COUNT as an issue per se ;) also, i suspect very few are going to be refreshing the page with devtools open except for, uh, us lol

**Comment by seijihariki** [comment]
On #60 canvas now starts at center. That should help a little, as resizing after page open should not expose the border anymore. (Unless you have a big monitor). Sincerely, if someone takes the time to open devtools and drag the screen to an edge, keeping it inside the viewport, then closes the devtools, that's on them.

**Comment by zero01101** [comment]
>On https://github.com/zero01101/openOutpaint/pull/60 viewport now starts at center of canvas. That should help a little

"a little" meaning it's completely alleviated in both firefox and chrome from what i can tell :D
